import { Edge } from 'reactflow';
import { FBlockNode } from './store';
import { extractParams } from './sandbox/runner';

/**
 * Kahn's algorithm — returns nodes in dependency order (sources before
 * their targets). Nodes participating in cycles are appended at the end
 * in their original order so nothing is silently dropped.
 */
export function topoSort(nodes: FBlockNode[], edges: Edge[]): FBlockNode[] {
  const idSet = new Set(nodes.map((n) => n.id));
  const inDegree = new Map<string, number>();
  const adj = new Map<string, string[]>();
  for (const n of nodes) {
    inDegree.set(n.id, 0);
    adj.set(n.id, []);
  }
  for (const e of edges) {
    if (!idSet.has(e.source) || !idSet.has(e.target)) continue;
    inDegree.set(e.target, (inDegree.get(e.target) || 0) + 1);
    adj.get(e.source)!.push(e.target);
  }
  const queue: FBlockNode[] = nodes.filter((n) => inDegree.get(n.id) === 0);
  const result: FBlockNode[] = [];
  while (queue.length > 0) {
    const n = queue.shift()!;
    result.push(n);
    for (const next of adj.get(n.id)!) {
      const newIn = (inDegree.get(next) || 0) - 1;
      inDegree.set(next, newIn);
      if (newIn === 0) {
        const nextNode = nodes.find((m) => m.id === next);
        if (nextNode) queue.push(nextNode);
      }
    }
  }
  const included = new Set(result.map((n) => n.id));
  for (const n of nodes) if (!included.has(n.id)) result.push(n);
  return result;
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((l) => (l.length > 0 ? pad + l : l))
    .join('\n');
}

function headerComment(commentPrefix: string, count: number): string {
  const plural = count === 1 ? '' : 's';
  return [
    `${commentPrefix} Generated by agent-coding-view`,
    `${commentPrefix} ${count} function block${plural}`,
    '',
  ].join('\n');
}

export function exportToJs(nodes: FBlockNode[]): string {
  return (
    headerComment('//', nodes.length) +
    nodes
      .map((n) => {
        const params = extractParams(n.data.signature);
        const body = n.data.body.trim() || '// body not generated yet';
        return `function ${n.data.name}(${params.join(', ')}) {\n${indent(body, 2)}\n}`;
      })
      .join('\n\n') +
    '\n'
  );
}

export function exportToPython(nodes: FBlockNode[]): string {
  return (
    headerComment('#', nodes.length) +
    nodes
      .map((n) => {
        const params = extractParams(n.data.signature);
        const body = n.data.body.trim() || 'pass  # body not generated yet';
        return `def ${n.data.name}(${params.join(', ')}):\n${indent(body, 4)}`;
      })
      .join('\n\n') +
    '\n'
  );
}

export interface ExportResult {
  filename: string;
  content: string;
}

/**
 * Export the subset of `nodes` whose effective language matches the
 * `language` argument, topologically sorted, as one flat source file.
 * Unsupported languages throw.
 */
export function exportGraph(
  nodes: FBlockNode[],
  edges: Edge[],
  language: string,
  defaultLanguage: string,
): ExportResult {
  const matching = nodes.filter((n) => (n.data.language || defaultLanguage) === language);
  const sorted = topoSort(matching, edges);

  if (language === 'javascript') {
    return { filename: `graph-${Date.now()}.js`, content: exportToJs(sorted) };
  }
  if (language === 'typescript') {
    // TS exporter currently emits JS-shaped output — parameter types are
    // dropped by extractParams, and bodies are language-neutral strings.
    // A richer TS exporter would re-attach annotations from the original
    // signature, but that's out of scope for the MVP.
    return { filename: `graph-${Date.now()}.ts`, content: exportToJs(sorted) };
  }
  if (language === 'python') {
    return { filename: `graph-${Date.now()}.py`, content: exportToPython(sorted) };
  }
  throw new Error(`Export not supported for language "${language}".`);
}

/**
 * Export every supported language that has at least one block assigned to
 * it (or inheriting through defaultLanguage). Returns a list of files the
 * caller can download one at a time. Order matches SUPPORTED_EXPORT_LANGS.
 */
const SUPPORTED_EXPORT_LANGS = ['javascript', 'typescript', 'python'] as const;

export function exportAllLanguages(
  nodes: FBlockNode[],
  edges: Edge[],
  defaultLanguage: string,
): ExportResult[] {
  const out: ExportResult[] = [];
  for (const lang of SUPPORTED_EXPORT_LANGS) {
    const matching = nodes.filter(
      (n) => (n.data.language || defaultLanguage) === lang,
    );
    if (matching.length === 0) continue;
    out.push(exportGraph(nodes, edges, lang, defaultLanguage));
  }
  return out;
}

/**
 * Render the graph as a Mermaid `flowchart LR`. Nodes carry status-based
 * CSS classes so downstream Mermaid themes can color them. Unlike the
 * source exports this is stable regardless of language and is meant for
 * pasting into markdown / docs / PR descriptions.
 *
 * Block names are sanitized to a Mermaid-safe id (letters/digits/underscore).
 * Collisions from sanitization get numeric suffixes so no two blocks share
 * an id — `foo/bar` and `foo.bar` both collapse to `foo_bar` otherwise.
 */
export function exportToMermaid(nodes: FBlockNode[], edges: Edge[]): string {
  const lines: string[] = ['flowchart LR'];
  // Sanitize: keep only word chars, then dedupe against prior ids.
  const safeIds = new Map<string, string>();
  const used = new Set<string>();
  for (const n of nodes) {
    let base = (n.data.name || n.id).replace(/[^\w]/g, '_') || 'node';
    if (/^\d/.test(base)) base = '_' + base;
    let candidate = base;
    let suffix = 2;
    while (used.has(candidate)) candidate = `${base}_${suffix++}`;
    used.add(candidate);
    safeIds.set(n.id, candidate);
  }
  for (const n of nodes) {
    const id = safeIds.get(n.id)!;
    // Escape `"` inside labels so the bracket form stays valid Mermaid.
    const label = (n.data.name || '(unnamed)').replace(/"/g, '#quot;');
    lines.push(`  ${id}["${label}"]:::status_${n.data.status}`);
  }
  const idSet = new Set(nodes.map((n) => n.id));
  for (const e of edges) {
    if (!idSet.has(e.source) || !idSet.has(e.target)) continue;
    lines.push(`  ${safeIds.get(e.source)} --> ${safeIds.get(e.target)}`);
  }
  // Class defs — Mermaid themes can override these, we just pick colors
  // that echo the in-app palette.
  lines.push('  classDef status_passing fill:#3ecf8e,stroke:#2a9d6f,color:#0f1115');
  lines.push('  classDef status_failing fill:#ff5d73,stroke:#c03b50,color:#0f1115');
  lines.push('  classDef status_generating fill:#ffd166,stroke:#c9a13f,color:#0f1115');
  lines.push('  classDef status_running_tests fill:#ffd166,stroke:#c9a13f,color:#0f1115');
  lines.push('  classDef status_specd fill:#5b8cff,stroke:#3a5fb0,color:#ffffff');
  lines.push('  classDef status_stub fill:#4a556e,stroke:#2f3647,color:#ffffff');
  return lines.join('\n') + '\n';
}
