import { describe, it, expect } from 'vitest';
import { Edge } from 'reactflow';
import {
  topoSort,
  exportToJs,
  exportToPython,
  exportGraph,
  exportAllLanguages,
  exportToMermaid,
} from './exporter';
import { FBlockNode } from './store';
import { defaultBlockData, FunctionBlockData } from './types';

function node(id: string, data: Partial<FunctionBlockData> = {}): FBlockNode {
  return {
    id,
    type: 'fblock',
    position: { x: 0, y: 0 },
    data: { ...defaultBlockData(id), ...data },
  };
}

function edge(source: string, target: string): Edge {
  return { id: `${source}-${target}`, source, target };
}

describe('topoSort', () => {
  it('empty graph returns empty', () => {
    expect(topoSort([], [])).toEqual([]);
  });

  it('single node returns itself', () => {
    const n = node('a');
    expect(topoSort([n], [])).toEqual([n]);
  });

  it('linear chain returns source before target', () => {
    const a = node('a');
    const b = node('b');
    const c = node('c');
    const result = topoSort([a, b, c], [edge('a', 'b'), edge('b', 'c')]);
    expect(result.map((n) => n.id)).toEqual(['a', 'b', 'c']);
  });

  it('diamond DAG puts the root first and the sink last', () => {
    const a = node('a');
    const b = node('b');
    const c = node('c');
    const d = node('d');
    const result = topoSort(
      [a, b, c, d],
      [edge('a', 'b'), edge('a', 'c'), edge('b', 'd'), edge('c', 'd')],
    );
    const order = result.map((n) => n.id);
    expect(order[0]).toBe('a');
    expect(order[3]).toBe('d');
  });

  it('cycle members are appended at the end, not dropped', () => {
    const a = node('a');
    const b = node('b');
    const c = node('c');
    // c has no cycle, a↔b do
    const result = topoSort([a, b, c], [edge('a', 'b'), edge('b', 'a')]);
    expect(result.map((n) => n.id).sort()).toEqual(['a', 'b', 'c']);
  });

  it('ignores edges that point to unknown nodes', () => {
    const a = node('a');
    const result = topoSort([a], [edge('a', 'ghost')]);
    expect(result).toEqual([a]);
  });
});

describe('exportToJs', () => {
  it('emits function declarations for each block', () => {
    const a = node('foo', {
      name: 'foo',
      signature: '(x) => number',
      body: 'return x * 2;',
    });
    const out = exportToJs([a]);
    expect(out).toContain('function foo(x) {');
    expect(out).toContain('return x * 2;');
    expect(out).toContain('Generated by agent-coding-view');
    expect(out).toContain('1 function block');
  });

  it('uses plural in header for multiple blocks', () => {
    const a = node('a', { name: 'a', signature: '()', body: 'return 1;' });
    const b = node('b', { name: 'b', signature: '()', body: 'return 2;' });
    expect(exportToJs([a, b])).toContain('2 function blocks');
  });

  it('indents the body by 2 spaces', () => {
    const a = node('foo', {
      name: 'foo',
      signature: '(x) => number',
      body: 'const y = x + 1;\nreturn y;',
    });
    const out = exportToJs([a]);
    expect(out).toContain('  const y = x + 1;');
    expect(out).toContain('  return y;');
  });

  it('stubs out blocks with no body', () => {
    const a = node('stub', { name: 'stub', signature: '(x)', body: '' });
    expect(exportToJs([a])).toContain('// body not generated yet');
  });

  it('strips TS type annotations from params in the output', () => {
    const a = node('fn', {
      name: 'fn',
      signature: '(raw: string, n: number = 2) => Parsed',
      body: 'return raw.repeat(n);',
    });
    const out = exportToJs([a]);
    expect(out).toContain('function fn(raw, n = 2) {');
  });
});

describe('exportToPython', () => {
  it('emits def statements with 4-space indent', () => {
    const a = node('py_foo', {
      name: 'py_foo',
      signature: 'def py_foo(x: int) -> int',
      body: 'return x * 2',
    });
    const out = exportToPython([a]);
    expect(out).toContain('def py_foo(x):');
    expect(out).toContain('    return x * 2');
    expect(out).toContain('# Generated by agent-coding-view');
  });

  it('stubs with pass for empty bodies', () => {
    const a = node('stub', { name: 'stub', signature: 'def stub(x)', body: '' });
    expect(exportToPython([a])).toContain('pass');
  });
});

describe('exportToJs runnability', () => {
  it('produces valid JavaScript that new Function() can parse', () => {
    const a = node('double', {
      name: 'double',
      signature: '(x) => number',
      body: 'return x * 2;',
    });
    const out = exportToJs([a]);
    // Prepend header stripping logic: header is just comments, fine to eval.
    expect(() => new Function(out)).not.toThrow();
  });

  it('functions can call each other when emitted in topological order', () => {
    const a = node('double', {
      name: 'double',
      signature: '(x) => number',
      body: 'return x * 2;',
    });
    const b = node('quadruple', {
      name: 'quadruple',
      signature: '(x) => number',
      body: 'return double(double(x));',
    });
    const sorted = topoSort([a, b], [edge('a', 'b')]);
    const out = exportToJs(sorted);
    // eslint-disable-next-line @typescript-eslint/no-implied-eval, no-new-func
    const run = new Function(`${out}\nreturn quadruple(3);`);
    expect(run()).toBe(12);
  });

  it('stub body still parses as JS', () => {
    const a = node('stub', { name: 'stub', signature: '(x)', body: '' });
    const out = exportToJs([a]);
    expect(() => new Function(out)).not.toThrow();
  });

  it('multi-statement body preserves statements', () => {
    const a = node('compute', {
      name: 'compute',
      signature: '(x, y)',
      body: 'const sum = x + y;\nconst prod = x * y;\nreturn sum + prod;',
    });
    const out = exportToJs([a]);
    // eslint-disable-next-line @typescript-eslint/no-implied-eval, no-new-func
    const run = new Function(`${out}\nreturn compute(3, 4);`);
    expect(run()).toBe(3 + 4 + 3 * 4);
  });
});

describe('exportGraph dispatch', () => {
  it('filters by effective language', () => {
    const nodes = [
      node('a', { name: 'jsOnly', language: 'javascript', body: 'return 1;' }),
      node('b', { name: 'pyOnly', language: 'python', body: 'return 2' }),
    ];
    const jsResult = exportGraph(nodes, [], 'javascript', 'javascript');
    expect(jsResult.content).toContain('jsOnly');
    expect(jsResult.content).not.toContain('pyOnly');

    const pyResult = exportGraph(nodes, [], 'python', 'javascript');
    expect(pyResult.content).toContain('pyOnly');
    expect(pyResult.content).not.toContain('jsOnly');
  });

  it('blocks with empty language inherit from defaultLanguage', () => {
    const a = node('a', { name: 'inherited', language: '', body: 'return 0;' });
    const result = exportGraph([a], [], 'javascript', 'javascript');
    expect(result.content).toContain('function inherited');
  });

  it('throws on unsupported languages', () => {
    expect(() => exportGraph([], [], 'brainfuck', 'javascript')).toThrow(/not supported/);
  });

  it('emits filename with correct extension', () => {
    expect(exportGraph([], [], 'javascript', 'javascript').filename).toMatch(/\.js$/);
    expect(exportGraph([], [], 'typescript', 'javascript').filename).toMatch(/\.ts$/);
    expect(exportGraph([], [], 'python', 'javascript').filename).toMatch(/\.py$/);
  });
});

describe('exportAllLanguages', () => {
  it('empty graph returns empty array', () => {
    expect(exportAllLanguages([], [], 'javascript')).toEqual([]);
  });

  it('only emits languages that have at least one block', () => {
    const nodes = [
      node('a', { name: 'jsOnly', language: 'javascript', body: 'return 1;' }),
      node('b', { name: 'pyOnly', language: 'python', body: 'return 2' }),
    ];
    const results = exportAllLanguages(nodes, [], 'javascript');
    expect(results).toHaveLength(2);
    expect(results.map((r) => r.filename.split('.').pop())).toEqual(['js', 'py']);
  });

  it('skips languages with no blocks', () => {
    const nodes = [node('a', { name: 'only', language: 'typescript', body: 'return 1;' })];
    const results = exportAllLanguages(nodes, [], 'javascript');
    // Blocks with explicit language=typescript; no js, no py.
    expect(results).toHaveLength(1);
    expect(results[0].filename).toMatch(/\.ts$/);
  });

  it('default-language inheritance puts unlabeled blocks into the default', () => {
    const nodes = [
      node('a', { name: 'inherited', language: '', body: 'return 1;' }),
      node('b', { name: 'explicit_py', language: 'python', body: 'return 2' }),
    ];
    const results = exportAllLanguages(nodes, [], 'javascript');
    const langs = results.map((r) => r.filename.split('.').pop());
    expect(langs).toContain('js');
    expect(langs).toContain('py');
    // TS has no blocks → skipped
    expect(langs).not.toContain('ts');
  });

  it('preserves language order: js → ts → py', () => {
    const nodes = [
      node('a', { name: 'py', language: 'python', body: 'return 1' }),
      node('b', { name: 'ts', language: 'typescript', body: 'return 2;' }),
      node('c', { name: 'js', language: 'javascript', body: 'return 3;' }),
    ];
    const results = exportAllLanguages(nodes, [], 'javascript');
    expect(results.map((r) => r.filename.match(/\.(\w+)$/)?.[1])).toEqual(['js', 'ts', 'py']);
  });
});

describe('exportToMermaid', () => {
  it('empty graph still has a flowchart header and class defs', () => {
    const out = exportToMermaid([], []);
    expect(out).toMatch(/^flowchart LR/);
    // Class defs are always emitted so themed output stays consistent.
    expect(out).toContain('classDef status_passing');
    expect(out).toContain('classDef status_failing');
  });

  it('emits one node line per block with a status class', () => {
    const nodes = [
      node('a', { name: 'parseInput', status: 'passing' }),
      node('b', { name: 'validate', status: 'failing' }),
    ];
    const out = exportToMermaid(nodes, []);
    expect(out).toContain('parseInput["parseInput"]:::status_passing');
    expect(out).toContain('validate["validate"]:::status_failing');
  });

  it('emits edge lines only for edges whose endpoints exist', () => {
    const nodes = [node('a', { name: 'x' }), node('b', { name: 'y' })];
    const edges = [edge('a', 'b'), edge('a', 'ghost')];
    const out = exportToMermaid(nodes, edges);
    expect(out).toContain('x --> y');
    expect(out).not.toContain('ghost');
  });

  it('sanitizes non-word chars in block names', () => {
    const nodes = [node('a', { name: 'foo/bar' }), node('b', { name: 'baz.qux' })];
    const out = exportToMermaid(nodes, []);
    // `/` and `.` become `_`, but the label keeps the original name.
    expect(out).toContain('foo_bar["foo/bar"]');
    expect(out).toContain('baz_qux["baz.qux"]');
  });

  it('dedupes sanitized ids that collide', () => {
    // Two different names collapse to the same sanitized id `foo_bar`.
    const nodes = [node('a', { name: 'foo/bar' }), node('b', { name: 'foo.bar' })];
    const out = exportToMermaid(nodes, []);
    // First one wins `foo_bar`, second gets a numeric suffix.
    expect(out).toContain('foo_bar["foo/bar"]');
    expect(out).toContain('foo_bar_2["foo.bar"]');
  });

  it('prefixes ids that begin with a digit', () => {
    const nodes = [node('a', { name: '1stThing' })];
    const out = exportToMermaid(nodes, []);
    expect(out).toContain('_1stThing["1stThing"]');
  });
});
