import { describe, it, expect } from 'vitest';
import { Edge } from 'reactflow';
import { topoSort, exportToJs, exportToPython, exportGraph } from './exporter';
import { FBlockNode } from './store';
import { defaultBlockData, FunctionBlockData } from './types';

function node(id: string, data: Partial<FunctionBlockData> = {}): FBlockNode {
  return {
    id,
    type: 'fblock',
    position: { x: 0, y: 0 },
    data: { ...defaultBlockData(id), ...data },
  };
}

function edge(source: string, target: string): Edge {
  return { id: `${source}-${target}`, source, target };
}

describe('topoSort', () => {
  it('empty graph returns empty', () => {
    expect(topoSort([], [])).toEqual([]);
  });

  it('single node returns itself', () => {
    const n = node('a');
    expect(topoSort([n], [])).toEqual([n]);
  });

  it('linear chain returns source before target', () => {
    const a = node('a');
    const b = node('b');
    const c = node('c');
    const result = topoSort([a, b, c], [edge('a', 'b'), edge('b', 'c')]);
    expect(result.map((n) => n.id)).toEqual(['a', 'b', 'c']);
  });

  it('diamond DAG puts the root first and the sink last', () => {
    const a = node('a');
    const b = node('b');
    const c = node('c');
    const d = node('d');
    const result = topoSort(
      [a, b, c, d],
      [edge('a', 'b'), edge('a', 'c'), edge('b', 'd'), edge('c', 'd')],
    );
    const order = result.map((n) => n.id);
    expect(order[0]).toBe('a');
    expect(order[3]).toBe('d');
  });

  it('cycle members are appended at the end, not dropped', () => {
    const a = node('a');
    const b = node('b');
    const c = node('c');
    // c has no cycle, a↔b do
    const result = topoSort([a, b, c], [edge('a', 'b'), edge('b', 'a')]);
    expect(result.map((n) => n.id).sort()).toEqual(['a', 'b', 'c']);
  });

  it('ignores edges that point to unknown nodes', () => {
    const a = node('a');
    const result = topoSort([a], [edge('a', 'ghost')]);
    expect(result).toEqual([a]);
  });
});

describe('exportToJs', () => {
  it('emits function declarations for each block', () => {
    const a = node('foo', {
      name: 'foo',
      signature: '(x) => number',
      body: 'return x * 2;',
    });
    const out = exportToJs([a]);
    expect(out).toContain('function foo(x) {');
    expect(out).toContain('return x * 2;');
    expect(out).toContain('Generated by agent-coding-view');
    expect(out).toContain('1 function block');
  });

  it('uses plural in header for multiple blocks', () => {
    const a = node('a', { name: 'a', signature: '()', body: 'return 1;' });
    const b = node('b', { name: 'b', signature: '()', body: 'return 2;' });
    expect(exportToJs([a, b])).toContain('2 function blocks');
  });

  it('indents the body by 2 spaces', () => {
    const a = node('foo', {
      name: 'foo',
      signature: '(x) => number',
      body: 'const y = x + 1;\nreturn y;',
    });
    const out = exportToJs([a]);
    expect(out).toContain('  const y = x + 1;');
    expect(out).toContain('  return y;');
  });

  it('stubs out blocks with no body', () => {
    const a = node('stub', { name: 'stub', signature: '(x)', body: '' });
    expect(exportToJs([a])).toContain('// body not generated yet');
  });

  it('strips TS type annotations from params in the output', () => {
    const a = node('fn', {
      name: 'fn',
      signature: '(raw: string, n: number = 2) => Parsed',
      body: 'return raw.repeat(n);',
    });
    const out = exportToJs([a]);
    expect(out).toContain('function fn(raw, n = 2) {');
  });
});

describe('exportToPython', () => {
  it('emits def statements with 4-space indent', () => {
    const a = node('py_foo', {
      name: 'py_foo',
      signature: 'def py_foo(x: int) -> int',
      body: 'return x * 2',
    });
    const out = exportToPython([a]);
    expect(out).toContain('def py_foo(x):');
    expect(out).toContain('    return x * 2');
    expect(out).toContain('# Generated by agent-coding-view');
  });

  it('stubs with pass for empty bodies', () => {
    const a = node('stub', { name: 'stub', signature: 'def stub(x)', body: '' });
    expect(exportToPython([a])).toContain('pass');
  });
});

describe('exportGraph dispatch', () => {
  it('filters by effective language', () => {
    const nodes = [
      node('a', { name: 'jsOnly', language: 'javascript', body: 'return 1;' }),
      node('b', { name: 'pyOnly', language: 'python', body: 'return 2' }),
    ];
    const jsResult = exportGraph(nodes, [], 'javascript', 'javascript');
    expect(jsResult.content).toContain('jsOnly');
    expect(jsResult.content).not.toContain('pyOnly');

    const pyResult = exportGraph(nodes, [], 'python', 'javascript');
    expect(pyResult.content).toContain('pyOnly');
    expect(pyResult.content).not.toContain('jsOnly');
  });

  it('blocks with empty language inherit from defaultLanguage', () => {
    const a = node('a', { name: 'inherited', language: '', body: 'return 0;' });
    const result = exportGraph([a], [], 'javascript', 'javascript');
    expect(result.content).toContain('function inherited');
  });

  it('throws on unsupported languages', () => {
    expect(() => exportGraph([], [], 'brainfuck', 'javascript')).toThrow(/not supported/);
  });

  it('emits filename with correct extension', () => {
    expect(exportGraph([], [], 'javascript', 'javascript').filename).toMatch(/\.js$/);
    expect(exportGraph([], [], 'typescript', 'javascript').filename).toMatch(/\.ts$/);
    expect(exportGraph([], [], 'python', 'javascript').filename).toMatch(/\.py$/);
  });
});
